bundler_args: --without guard

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
